hrmsystem.web/Controllers/AttendanceController.cs
using hrmsystem.datamodels;
using hrmsystem.viewmodels;
using hrmsystem.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace hrmsystem.web.Controllers
{
    public class AttendanceController : Controller
    {
        public EmployeeServices employeeServices;
        public AttendanceServices attendanceServices;

        public AttendanceController(EmployeeServices _employeeServices, AttendanceServices _attendanceServices)
        {
            this.employeeServices = _employeeServices;
            this.attendanceServices = _attendanceServices;
        }

        public async Task<IActionResult> AttendanceList()
        {
            List<VMTblAttendance> data = await attendanceServices.GetAllData();
            return View(data);
        }

        public async Task<IActionResult> AddAttendance()
        {
            VMTblAttendance data = new VMTblAttendance();
            List<VMTblEmployees> listEmployee = await employeeServices.GetAllData();
            ViewBag.ListEmployee = listEmployee;
            ViewBag.ListPlace = new List<VMDropDown>()
            {
                new VMDropDown{Value = "Office", Name = "Office" },
                new VMDropDown{Value = "Field", Name = "Field" }
            };
            return View(data);
        }
		[HttpPost]
		public async Task<IActionResult> AddAttendance(VMTblAttendance dataParam)
		{
			VMResponse respon = await attendanceServices.AddAttendance(dataParam);
			if (respon.Success)
			{
				return Json(new { dataRespon = respon });
			}
			return View(dataParam);
		}

        public async Task<IActionResult> EditAttendance(int id)
        {
            VMTblAttendance data = await attendanceServices.GetDataById(id);
			List<VMTblEmployees> listEmployee = await employeeServices.GetAllData();
			ViewBag.ListEmployee = listEmployee;
			ViewBag.ListPlace = new List<VMDropDown>()
			{
				new VMDropDown{Value = "Office", Name = "Office" },
				new VMDropDown{Value = "Field", Name = "Field" }
			};
			return PartialView(data);
        }

		public async Task<IActionResult> AttendanceReport()
        {
            return View();
        }

        public async Task<IActionResult> AddBulkAttendance()
        {
            return View();
        }
    }
}

hrmsystem.web/Views/Shared/_Footer.cshtml
<!-- FOOTER -->
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-md-12 col-sm-12 text-center">
                Copyright © <span id="year"></span> <a href="javascript:void(0)">Sash</a>. Designed with <span class="fa fa-heart text-danger"></span> by <a href="javascript:void(0)"> Spruko </a> All rights reserved.
            </div>
        </div>
    </div>
</footer>
<!-- FOOTER END -->

hrmsystem.web/Views/Shared/_Header.cshtml
  <!-- app-Header -->
<div class="app-header header sticky">
    <div class="container-fluid main-container">
        <div class="d-flex">
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar" href="javascript:void(0)"></a>
            <!-- sidebar-toggle-->
            <a class="logo-horizontal " href="index.html">
                <img src="../assets/images/brand/logo-white.png" class="header-brand-img desktop-logo" alt="logo">
                <img src="../assets/images/brand/logo-dark.png" class="header-brand-img light-logo1"
                     alt="logo">
            </a>
            <!-- LOGO -->
            
            <div class="d-flex order-lg-2 ms-auto header-right-icons">
                
                <button class="navbar-toggler navresponsive-toggler d-lg-none ms-auto" type="button"
                        data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4"
                        aria-controls="navbarSupportedContent-4" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fe fe-more-vertical"></span>
                </button>
                <!-- NOTIFICATIONS -->
                <div class="dropdown  d-flex notifications">
                    <a class="nav-link icon" data-bs-toggle="dropdown">
                        <i class="fe fe-bell"></i><span class=" pulse"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                        <div class="drop-heading border-bottom">
                            <div class="d-flex">
                                <h6 class="mt-1 mb-0 fs-16 fw-semibold text-dark">
                                    Notifications
                                </h6>
                            </div>
                        </div>
                        <div class="notifications-menu">
                            <a class="dropdown-item d-flex" href="notify-list.html">
                                <div class="me-3 notifyimg  bg-primary brround box-shadow-primary">
                                    <i class="fe fe-mail"></i>
                                </div>
                                <div class="mt-1 wd-80p">
                                    <h5 class="notification-label mb-1">
                                        New Application received
                                    </h5>
                                    <span class="notification-subtext">3 days ago</span>
                                </div>
                            </a>
                            <a class="dropdown-item d-flex" href="notify-list.html">
                                <div class="me-3 notifyimg  bg-secondary brround box-shadow-secondary">
                                    <i class="fe fe-check-circle"></i>
                                </div>
                                <div class="mt-1 wd-80p">
                                    <h5 class="notification-label mb-1">
                                        Project has been
                                        approved
                                    </h5>
                                    <span class="notification-subtext">2 hours ago</span>
                                </div>
                            </a>
                            <a class="dropdown-item d-flex" href="notify-list.html">
                                <div class="me-3 notifyimg  bg-success brround box-shadow-success">
                                    <i class="fe fe-shopping-cart"></i>
                                </div>
                                <div class="mt-1 wd-80p">
                                    <h5 class="notification-label mb-1">
                                        Your Product Delivered
                                    </h5>
                                    <span class="notification-subtext">30 min ago</span>
                                </div>
                            </a>
                            <a class="dropdown-item d-flex" href="notify-list.html">
                                <div class="me-3 notifyimg bg-pink brround box-shadow-pink">
                                    <i class="fe fe-user-plus"></i>
                                </div>
                                <div class="mt-1 wd-80p">
                                    <h5 class="notification-label mb-1">Friend Requests</h5>
                                    <span class="notification-subtext">1 day ago</span>
                                </div>
                            </a>
                        </div>
                        <div class="dropdown-divider m-0"></div>
                        <a href="notify-list.html"
                           class="dropdown-item text-center p-3 text-muted">
                            View all
                            Notification
                        </a>
                    </div>
                </div>
                <!------------------>
                <div class="navbar navbar-collapse responsive-navbar p-0">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                        <div class="d-flex order-lg-2">
                            
                           
                           
                            <!-- Theme-Layout -->
                            <div class="d-flex">
                                <a class="nav-link icon theme-layout nav-link-bg layout-setting">
                                    <span class="dark-layout"><i class="fe fe-moon"></i></span>
                                    <span class="light-layout"><i class="fe fe-sun"></i></span>
                                </a>
                            </div>
                            <!------------------>                          
                            
                            <!-- FULL-SCREEN -->
                            <div class="dropdown d-flex">
                                <a class="nav-link icon full-screen-link nav-link-bg">
                                    <i class="fe fe-minimize fullscreen-button"></i>
                                </a>
                            </div>
                            <!------------------>


                            <!-- Profile -->
                            <div class="dropdown d-flex profile-1">
                                <a href="javascript:void(0)" data-bs-toggle="dropdown" class="nav-link leading-none d-flex">
                                    <img src="../assets/images/users/21.jpg" alt="profile-user"
                                         class="avatar  profile-user brround cover-image">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                    <div class="drop-heading">
                                        <div class="text-center">
                                            <h5 class="text-dark mb-0 fs-14 fw-semibold">Percy Kewshun</h5>
                                            <small class="text-muted">Senior Admin</small>
                                        </div>
                                    </div>
                                    <div class="dropdown-divider m-0"></div>
                                    <a class="dropdown-item" href="profile.html">
                                        <i class="dropdown-icon fe fe-user"></i> My Profile
                                    </a>
                                    <a class="dropdown-item" href="email-inbox.html">
                                        <i class="dropdown-icon fe fe-settings"></i> Account Setting
                                    </a>                                 
                                    <a class="dropdown-item" href="login.html">
                                        <i class="dropdown-icon fe fe-log-out"></i> Logout
                                    </a>
                                </div>
                            </div>
                            <!------------------>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!---- /app-Header ---->

hrmsystem.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hrmsystem.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hrmsystem.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">hrmsystem.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - hrmsystem.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

hrmsystem.web/Views/Shared/_LayoutSash.cshtml
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="HRM System">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords"
          content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="../assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>HRM System</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="../assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
    <link href="../assets/css/style.css" rel="stylesheet">

    <!-- Plugins CSS -->
    <link href="../assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="../assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="../assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="../assets/switcher/demo.css" rel="stylesheet">

</head>

<body class="app sidebar-mini ltr light-mode">


    <!-- GLOBAL-LOADER -->
    <div id="global-loader">
        <img src="../assets/images/loader.svg" class="loader-img" alt="Loader">
    </div>
    <!-- /GLOBAL-LOADER -->

    <partial name="_Header" />
    <partial name="_Sidebar" />

    <!-- PAGE -->
    <div class="page">
        <div class="page-main">
            <div class="main-content app-content mt-0">
                <div class="side-app">
                    <!-- CONTAINER -->
                    <div class="main-container container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <partial name="_Footer" />
    <a href="#top" id="back-to-top"><i class="fa fa-angle-up"></i></a>

    <!-- JQUERY JS -->
    <script src="../assets/js/jquery.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="../assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="../assets/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- SPARKLINE JS-->
    <script src="../assets/js/jquery.sparkline.min.js"></script>

    <!-- Sticky js -->
    <script src="../assets/js/sticky.js"></script>

    <!-- CHART-CIRCLE JS-->
    <script src="../assets/js/circle-progress.min.js"></script>

    <!-- PIETY CHART JS-->
    <script src="../assets/plugins/peitychart/jquery.peity.min.js"></script>
    <script src="../assets/plugins/peitychart/peitychart.init.js"></script>

    <!-- SIDEBAR JS -->
    <script src="../assets/plugins/sidebar/sidebar.js"></script>

    <!-- Perfect SCROLLBAR JS-->
    <script src="../assets/plugins/p-scroll/perfect-scrollbar.js"></script>
    <script src="../assets/plugins/p-scroll/pscroll.js"></script>
    <script src="../assets/plugins/p-scroll/pscroll-1.js"></script>

    <!-- INTERNAL CHARTJS CHART JS-->
    <script src="../assets/plugins/chart/Chart.bundle.js"></script>
    <script src="../assets/plugins/chart/utils.js"></script>

    <!-- INTERNAL SELECT2 JS -->
    <script src="../assets/plugins/select2/select2.full.min.js"></script>

    <!-- INTERNAL Data tables js-->
    <script src="../assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.bootstrap5.js"></script>
    <script src="../assets/plugins/datatable/dataTables.responsive.min.js"></script>

    <!-- INTERNAL APEXCHART JS -->
    <script src="../assets/js/apexcharts.js"></script>
    <script src="../assets/plugins/apexchart/irregular-data-series.js"></script>

    <!-- INTERNAL Flot JS -->
    <script src="../assets/plugins/flot/jquery.flot.js"></script>
    <script src="../assets/plugins/flot/jquery.flot.fillbetween.js"></script>
    <script src="../assets/plugins/flot/chart.flot.sampledata.js"></script>
    <script src="../assets/plugins/flot/dashboard.sampledata.js"></script>

    <!-- INTERNAL Vector js -->
    <script src="../assets/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="../assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

    <!-- SIDE-MENU JS-->
    <script src="../assets/plugins/sidemenu/sidemenu.js"></script>

    <!-- TypeHead js -->
    <script src="../assets/plugins/bootstrap5-typehead/autocomplete.js"></script>
    <script src="../assets/js/typehead.js"></script>

    <!-- INTERNAL INDEX JS -->
    <script src="../assets/js/index1.js"></script>

    <!-- Color Theme js -->
    <script src="../assets/js/themeColors.js"></script>

    <!-- CUSTOM JS -->
    <script src="../assets/js/custom.js"></script>

    <!-- Custom-switcher -->
    <script src="../assets/js/custom-swicher.js"></script>

    <!-- Switcher js -->
    <script src="../assets/switcher/js/switcher.js"></script>

</body>

</html>

hrmsystem.web/Views/Shared/_Sidebar.cshtml
 <!--APP-SIDEBAR-->
<div class="sticky">
	<div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
	<div class="app-sidebar">
		<div class="side-header">
			<a class="header-brand1" href="index.html">
				<img src="../assets/images/brand/logo-white.png" class="header-brand-img desktop-logo" alt="logo">
				<img src="../assets/images/brand/icon-white.png" class="header-brand-img toggle-logo"
					 alt="logo">
				<img src="../assets/images/brand/icon-dark.png" class="header-brand-img light-logo" alt="logo">
				<img src="../assets/images/brand/logo-dark.png" class="header-brand-img light-logo1"
					 alt="logo">
			</a>
		<!-- LOGO -->
		</div>



		<div class="main-sidemenu">
			<div class="slide-left disabled" id="slide-left">
				<svg xmlns="http://www.w3.org/2000/svg"
					 fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
					<path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
				</svg>
			</div>
			<ul class="side-menu">
				
				<!-- DASHBOARD -->
				<li class="slide">
					<a class="side-menu__item has-link" data-bs-toggle="slide" href="index.html">
						<i class="side-menu__icon fe fe-home"></i><span class="side-menu__label">Dashboard</span>
					</a>
				</li>
				<!-- ORGANIZATION -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fa fa-building-o"></i>
						<span class="side-menu__label">Organization</span>
						<i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu ">
						<li class="panel sidetab-menu">
							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active">
										<ul class="sidemenu-list">											
											<li><a  class="slide-item"> Department</a></li>
											<li><a  class="slide-item"> Designation</a></li>
										</ul>
									</div>

								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- EMPLOYEES -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fe fe-users"></i><span class="side-menu__label">Employees</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active">
										<ul class="sidemenu-list">
											<li><a  class="slide-item"> Employees</a></li>
											<li><a  class="slide-item"> Disciplinary</a></li>
											<li><a  class="slide-item"> Inactive User</a></li>

										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- ATTENDANCE -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon bi-calendar2-check"></i><span class="side-menu__label">Attendance</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active" >
										<ul class="sidemenu-list">
											<li><a class="slide-item" asp-controller="Attendance" asp-action="AttendanceList"> Attendance List</a></li>
											<li><a class="slide-item" asp-controller="Attendance" asp-action="AddAttendance"> Add Attendance</a></li>
											<li><a class="slide-item" asp-controller="Attendance" asp-action="AttendanceReport"> Attendance Report</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- LEAVE -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fe fe-user-x"></i><span class="side-menu__label">Leave</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active" >
										<ul class="sidemenu-list">
											<li><a class="slide-item"> Holiday</a></li>
											<li><a class="slide-item"> Leave Type</a></li>
											<li><a class="slide-item"> Leave Application</a></li>
											<li><a class="slide-item"> Earned Leave</a></li>
											<li><a class="slide-item"> Report</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- PROJECT -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon ion-clipboard"></i><span class="side-menu__label">Project</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active" >
										<ul class="sidemenu-list">
											<li><a class="slide-item"> Projects</a></li>
											<li><a class="slide-item"> Task List</a></li>
											<li><a class="slide-item"> Field Visit</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- PAYROLL -->				
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon ti-receipt"></i><span class="side-menu__label">Payroll</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active" >
										<ul class="sidemenu-list">
											<li><a class="slide-item"> Payroll List</a></li>
											<li><a class="slide-item"> Generate Payslip</a></li>
											<li><a class="slide-item"> Payslip Report</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- LOAN -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fa fa-money"></i><span class="side-menu__label">Loan</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active">
										<ul class="sidemenu-list">
											<li><a class="slide-item"> Grant Loan</a></li>
											<li><a class="slide-item"> Loan Installment</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- ASSETS -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fe fe-grid"></i><span class="side-menu__label">Assets</span><i class="angle fe fe-chevron-right"></i>
					</a>
					<ul class="slide-menu">
						<li class="panel sidetab-menu">

							<div class="panel-body tabs-menu-body p-0 border-0">
								<div class="tab-content">
									<div class="tab-pane active" >
										<ul class="sidemenu-list">
											<li><a class="slide-item"> Assets Category</a></li>
											<li><a class="slide-item"> Assets List</a></li>
											<li><a class="slide-item"> Logistic Support</a></li>
										</ul>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
				<!-- NOTICE -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fe fe-bell"></i><span class="side-menu__label">Notice</span>
					</a>
				</li>
				<!-- SETTING -->
				<li class="slide">
					<a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
						<i class="side-menu__icon fe fe-settings"></i><span class="side-menu__label">Setting</span>
					</a>
				</li>
			</ul>


			<div class="slide-right" id="slide-right">
				<svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191"
					 width="24" height="24" viewBox="0 0 24 24">
					<path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
				</svg>
			</div>
		</div>
	</div>
</div>
<!--/APP-SIDEBAR-->