hrmsystem.web/Controllers/DesignationController.cs
using Azure;
using hrmsystem.datamodels;
using hrmsystem.web.Services;
using Microsoft.AspNetCore.Mvc;
using xpos314.viewmodels;

namespace hrmsystem.web.Controllers
{
    public class DesignationController : Controller
    {
        private readonly DesignationServices designationServices;
        public int IdUser = 1;

        public DesignationController(DesignationServices _designationServices)
        {
            this.designationServices = _designationServices;
        }

        public async Task<IActionResult> Index()
        {
            List<TblDesignation> data = await designationServices.GetAllData();

            return View(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string nameDesignation)
        {
            bool isExist = await designationServices.CheckDesignationByName(nameDesignation);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblDesignation dataParam)
        {
            VMResponse respon = await designationServices.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblDesignation data = await designationServices.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TblDesignation dataParam)
        {
            dataParam.ModifiedBy = IdUser;
            VMResponse respon = await designationServices.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await designationServices.Delete(id);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            else
            {
                return RedirectToAction("Index", id);
            }
        }


    }
}

hrmsystem.web/Views/Designation/Edit.cshtml
@using hrmsystem.datamodels
@model TblDesignation
@{
    ViewData["Title"] = "Edit Designation";
}
<div class="card mb-lg-0">
    <div class="card-body mb-lg-0">
        <h4 mb-2>@ViewData["Title"]</h4>
        <form id="form_edit">
            <input type="hidden" id="Id" name="Id" value="@Model.Id">
            <div class="form-group row mb-2">
                <label for="DesignationName" class="col-sm-4 col-form-label">Designation Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="DesignationName" id="DesignationName" value="@Model.DesignationName">
                </div>
            </div>
            <div class="modal-footer mb-lg-0">
                <button type="submit" class="btn btn-primary btn-pill">Submit</button>
                <a class="btn btn-secondary btn-pill btn-test" asp-controller="Designation" asp-action="Index">Back</a>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function () {
    $("#form_edit").validate({
        errorClass: "text-danger",
        rules: {
            DesignationName: {
                required: true,
                minlength: 8,
            }
        },
        messages: {
            DesignationName: {
                required: "Please fill name Designation!",
                minlength: "The Name must consist of at least 8 character!",
            }
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();
            $.ajax({
                url: "/Designation/Edit",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#myModal").modal("hide");
                        Swal.fire({
                            icon: 'success',
                            title: 'Data has been updated',
                            showConfirmButton: false,
                            timer: 1500
                        })
                        setTimeout(function () {
                            window.location.reload();
                        }, 1600);
                    }
                    else {
                        Swal.fire({
                            icon: 'error',
                            title: data.message
                        });
                    }
                }
            })
        }
    })
});
</script>

hrmsystem.web/Views/Designation/Index.cshtml
@using hrmsystem.datamodels

<!-- PAGE-HEADER -->
<div class="page-header">
    <h1 class="page-title">Designation</h1>
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Designation</li>
        </ol>
    </div>
</div>
<!-- PAGE-HEADER END -->
<div class="row">
    <div class="col-md-12 col-xl-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add Designation</h4>
            </div>
            <div class="card-body">
                <form id="form_input">
                    <div class="    ">
                        <div class="form-group">
                            <label for="DesignationName" class="form-label">Designation Name</label>
                            <input type="text" class="form-control" id="DesignationName" name="DesignationName" placeholder="Enter DesignationName">
                            <span class="text-danger" id="validate_NameDesignation"></span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-pill btn-primary mt-4 mb-0">Save</button>
                    <button id="btn_cancel" class="btn btn-pill btn-danger mt-4 mb-0">Cancel</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Designation List</h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table border text-nowrap text-md-nowrap table-striped mb-0">
                        <thead>
                            <tr>
                                <th>Designation</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                             @if (Model.Count != 0)
                                {
                                    @foreach (var item in Model)
                                    {
                            <tr>
                                <td>@item.DesignationName</td>
                                <td class ="text-center align-middle">
                                            <a class="btn btn-sm btn-primary btn-pill btn_edit"  style="color: white" dataid="@item.Id"><i class="fe fe-edit"></i></a> &nbsp;
                                            <a class="btn btn-sm btn-danger btn-pill btn_delete" style="color: white" nama="@item.DesignationName" dataid="@item.Id"><i class="fe fe-trash-2"></i></a>
                                </td>
                            </tr>
                                    }
                            }
                            else
                            {
                                <tr>
                                    <td class="text-center align-middle" colspan="2">
                                        <i>Data not found</i>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")
        $("#myModal_body").empty();
        $("#myModal_body").load("/Designation/Edit?id=" + id)
        $("#myModal").modal("show");
    });

    $("#btn_cancel").click(function(){
        $("#DesignationName").val("")  
        $("#validate_NameDesignation").empty()
    });

    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")
        var name = $(this).attr("nama")

        Swal.fire({
            title: 'Are you sure delete this' + name + '?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: "/Designation/SureDelete?id=" + id,
                    type: "POST",
                    dataType: "json",
                    success: function (respon) {
                        var data = respon.dataRespon
                        if (data.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Data has been deleted',
                                showConfirmButton: false,
                                timer: 1500
                            })
                            setTimeout(function () {
                                window.location.reload();
                            }, 1600);
                        }
                        else {
                            Swal.fire({
                                icon: 'error',
                                title: data.message
                            });
                        }
                    }
                })
            }
        })
    });

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            DesignationName: {
                    required: true,
                    minlength: 8,
            }
        },
        messages: {
            DesignationName: {
                required: "Please fill name Designation!",
                minlength: "The Name must consist of at least 8 character!",
            }
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();
            var nameDesignation = $('#DesignationName').val();

            $.ajax({
                url: "/Designation/CheckNameIsExist",
                //method: "GET"
                type: "GET",
                data: { nameDesignation: nameDesignation },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameDesignation").text("Name Designation is already exist")
                        return true
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }
            })
        }
    })

    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Designation/Create",
            type: "POST",
            dataType: "json",
            data: dataParam,
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Data has been saved',
                        showConfirmButton: false,
                        timer: 1500
                    })
                    setTimeout(function () {
                        window.location.reload();
                    }, 1600);
                }
                else {
                    Swal.fire({
                        icon: 'error',
                        title: data.message
                    });
                }
            }
        })
    }

</script>